//API 1
GET http://localhost:3000/players/

###
// API 2

POST http://localhost:3000/players/
Content-Type: application/json

{
  "playerName": "Ramesh",
  "jerseyNumber": 21,
  "role": "Bowler"
}

### 
// API 3
GET http://localhost:3000/players/14/


###
//API 4
PUT http://localhost:3000/players/14/
Content-Type: application/json

{
"playerName": "Sunil",
  "jerseyNumber": 08,
  "role": "All-rounder"
}

### 
// API 5 
DELETE http://localhost:3000/players/12/